image: node:10.15.3

cache:
  paths:
  - node_modules
  key: ${CI_COMMIT_REF_SLUG}

build:
  script: npm install --silent
  stage: build
  only:
  - demo/module10/test_3

unit-test-client:
  stage: test
  script: npm run test:unit:client -- --silent
  only:
  - demo/module10/test_3

unit-test-server:
  stage: test
  script: npm run test:unit:server -- --silent
  only:
  - demo/module10/test_3
  services:
  - mongo:3.6.11
  variables:
  - JWT_SECRET: f0v89dj0df98
  - NODE_ENV: test
  - DB_NAME_TEST: printbay_test
  - MONGO_DB_URL: mongo://mongo:27017
