image: node:10.15.3

cache:
  paths:
    - node_modules
  key: ${CI_COMMIT_REF_SLUG}

variables:
  JWT_SECRET: ds9d87j92j9
  DB_NAME_TEST: printbay_test
  MONGO_DB_URI: mongodb://mongo:27017

build:
  script: npm install --silent
  stage: build
  only:
    - site

unit-test-client:
  stage: test
  script: npm run test:unit:client
  only:
    - site

unit-test-server:
  stage: test
  script: npm run test:unit:server
  only:
    - site
  services:
    - mongo:3.6.11
  variables:
    NODE_ENV: test

e2e-test:
  stage: test
  only:
    - site
  script: npm run test:e2e
  image: circleci/node:10.15.3-browsers
  services:
    - mongo:3.6.11
  variables:
    NODE_ENV: production

deploy:
  stage: deploy
  only:
    - site
  image: tmaier/dpl
  script: dpl --provider=heroku --app=$LIVE_APP_NAME --api-key=$LIVE_API_KEY
