image: node:10.15.3

cache:
  paths:
  - node_modules
  key: ${CI_COMMIT_REF_SLUG}

build:
  script: npm install --silent
  stage: build
  only:
  - demo/module10/test_3

unit-test-client:
  stage: test
  script: npm run test:unit:client -- --silent
  only:
  - demo/module10/test_3

unit-test-server:
  stage: test
  script: npm run test:unit:server -- --silent
  only:
  - demo/module10/test_3
  services:
  - mongo:3.6.11
  variables:
    NODE_ENV: test

e2e-test:
  stage: test
  only:
  - demo/module10/test_3
  script: npm run test:e2e -- --silent
  image: circleci/node:10.15.3-browsers
  services:
  - mongo:3.6.11
  variables:
    NODE_ENV: production

variables:
  JWT_SECRET: f0v89dj0df98
  DB_NAME_TEST: printbay_test
  MONGO_DB_URI: mongodb://mongo:27017

deploy:
  stage: deploy
  only:
  - demo/module10/test_3
  image: tmaier/dpl
  script: dpl --provider=heroku --app=${HEROKU_APP_NAME} --api-key=${HEROKU_API_KEY}
