image: node:10.15.3

cache:
  paths:
  - node_modules
  key: ${CI_COMMIT_REF_SLUG}

build:
  script: npm install --silent
  stage: build
  only:
  - demo/module10/test_3

unit-test-client:
  stage: test
  script: npm run test:unit:client -- --silent
  only:
  - demo/module10/test_3
